/**
 * 
 */
package org.flowninja.types.net;

/**
 * @author rainer
 *
 */
public enum ICMPType {
	ECHO_REPLY,
	DESTINATION_UNREACHABLE,
	SOURCE_QUENCH,
	REDIRECT,
	ALTERNATE_HOST_ADDRESS,
	ECHO,
	ROUTER_ADVERTISEMENT,
	ROUTER_SELECTION,
	TIME_EXCEEDED,
	PARAMETER_PROBLEM,
	TIMESTAMP,
	TIMESTAMP_REPLY,
	INFORMATION_REQUEST,
	INFORMATION_REPLY,
	ADDRESS_MASK_REQUEST,
	ADDRESS_MASK_REPLY,
	TRACEROUTE,
	DATAGRAM_CONVERSION_ERROR,
	MOBILE_HOST_REDIRECT,
	IPv6_WHERE_ARE_YOU,
	IPv6_I_AM_HERE,
	MOBILE_REGISTRATION_REQUEST,
	MOBILE_REGISTRATION_REPLY,
	DOMAIN_NAME_REQUEST,
	DOMAIN_NAME_REPLY,
	SKIP,
	PHOTURIS,
	UNASSIGNED
}
