/**
 * 
 */
package org.flowninja.types.net;

/**
 * @author rainer
 *
 */
public enum ICMPCode {
	UNASSIGNED,
	NO_CODE,
	
	// Type 3 - Destination unreachable
	NET_UNREACHABLE,
	HOST_UNREACABLE,
	PROTOCOL_UNREACHABLE,
	PORT_UNREACHABLE,
	FRAGMENTATION_NEEDED,
	SOURCE_ROUTE_FAILED,
	DESTINATION_NETWORK_UNKNWON,
	DESTINATION_HOST_UNKNOWN,
	SOURCE_HOST_ISOLATED,
	COMMUNICATION_DESTINATION_NETWORK_ADMINSTRATIVELY_PROHIBITED,
	COMMUNICATION_DESTINATION_HOST_ADMINSTRATIVELY_PROHIBITED,
	DESTINATION_NETWORK_UNREACHABLE,
	DESTINATION_HOST_UNREACHABLE,
	COMMUNICATION_ADMINSTRATIVELY_PROHIBITED,
	HOST_PRECEDENCE_VIOLATION,
	PRECEDENCE_CUTOFF,
	
	// Type 5 - Redirect
	REDIRECT_FOR_NETWORK,
	REDIRECT_FOR_HOST,
	REDIRECT_FOR_TOS_AND_NETWORK,
	REDIRECT_FOR_TOS_AND_HOST,
	
	// Type 6 - Alternate Host Address
	ALTERNATE_ADDRESS_FOR_HOST,
	
	// Type 9 - Router advertisement
	NORMAL_ROUTER_ADVERTISEMENT,
	DOES_NOT_ROUTE_COMMON_TRAFFIC,
	
	// Type 11 - Time exceeded
	TTL_EXCEED_IN_TRANSIT,
	REASSEMABLY_TIME_EXCEEDED,
	
	// Type 12 - Parameter problem
	POINTER_INDICATES_ERROR,
	MISSING_REQUIRED_OPTION,
	BAD_LENGTH,
	
	// Type 40 - Photuris
	BAD_SPI,
	AUTHENTICATION_FAILED,
	DECOMPRESSION_FAILED,
	DECRYPTION_FAILED,
	NEED_AUTHENTICATION,
	NEED_AUTHORIZATION
}
